### PR TITLE
Making rlbot upgrades take immediate effect.

### PR DESCRIPTION
**Pull request by tarehart**
Formerly, we would upgrade but then still run the previous version (at least partially) since many rlbot modules were already in sys.modules.

If this goes well, I'll paste it to the other repos.

### CODE REVIEW

**Comment by nevercast** [comment]
How many modules are you expecting start with rlbot? If its just one we can match it exactly, otherwise can we expose something in the modules that indicate they are RLBot library files? e.g. 

```
for rlbot_module in rlbots:
    if hasattr(rlbot, '__RLBOTLIB__'):
        sys.modules.pop(rlbot_module)
```

or even put that in the comprehension.
`[module for module in sys.modules if hasattr(module, '__RLBOTLIB__')]`

Thoughts?

I'm just concerned that the approach of `startswith` may not be precise. Though I'm sure its safe for now.

**Comment by tarehart** [comment]
We need to catch all the submodules like rlbot.version, rlbot.utils, etc.

The only way for there to be false positives would be if we imported something in *this* file and for some reason wanted to keep it in sys.modules. I don't see that happening, so I think we're good.

**Review by nevercast — APPROVED** [review]
We don't have a policy on extra white space do we? 😄 
LGTM 🎉

**Comment by nevercast** [comment]
Just for completeness, I'll say I now agree with you. Looking at the amount of subpackages, this is the most elegant solution. If anyone steps on our rlbot namespace that is their fault. We can always introduce an `rlbot.ext` namespace we ignore, if someone so needs a year in the future.

**Comment by nevercast** [comment]
Go ahead and delete the branch @tarehart if you've no further use for it. 👍

**Pull request merged**
