### PR TITLE
Add numpy utilities and game data pre-processing

### PR DESCRIPTION
**Pull request by ViliamVadocz**
The utilities should be well documented and easy to use.

### CODE REVIEW

**Comment by tarehart** [comment]
I like the idea of providing these utils for people who prefer to work with numpy. I'm concerned that it currently clashes with the rest of bot.py though because it's using the Vec3 class everywhere else.

Would you be willing to change this so it's just np_data.py and np_utils.py, and leave bot.py alone to avoid confusing anyone? Or in bot.py you could just have a comment like "Do you prefer to work with numpy? If so, you can find some utils in [folder]"

**Comment by ViliamVadocz** [comment]
Good point, although if we plan to use RLU there will be clashes anyway. I moved the utilities to a separate folder and removed the example code from `bot.py`.

**Comment by tarehart** [comment]
Great, thank you! Could you also remove the commented out code and make function names like a3v more descriptive?

For RLU was thinking of making a nice little wrapper function for aerials that takes Vec3 args

**Comment by ViliamVadocz** [comment]
`a3l`, `a3v`, and `a3r` are meant to be shorthand for converting other object types to numpy arrays. Although with good auto-complete suggestions it doesn't take much longer to write.

The commented out code is there so that you don't process things you don't use. If you do decide to use it you don't have to do any more work; just uncomment.

**Comment by tarehart** [comment]
Looks good, thanks Will!

**Pull request merged**
